# Generated by Django 5.0.6 on 2024-05-21 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='apellido',
            field=models.CharField(default='Sin apeillido', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(default='Sin cliente', max_length=255),
        ),
    ]
