# Generated by Django 5.0.6 on 2024-05-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_remove_pedido_productos_pedido_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='e_commerce.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=255),
        ),
    ]
