# Generated by Django 5.0.6 on 2024-05-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_remove_pedido_producto_pedido_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.CharField(default='Sin apellido', max_length=255),
        ),
    ]
