# Generated by Django 5.0.6 on 2024-05-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_remove_pedido_productos_pedido_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente',
            new_name='nombre',
        ),
    ]
